### ISSUE TITLE
Google Sync blows up if "TaskBridge" tag is missing.

### ISSUE THREAD

**Issue by johntrandall** [viamin/task_bridge#99]
When ENV is like this:
```
SYNC_SERVICES=GoogleTasks
SYNC_TAGS=TaskBridge
```

And OmniFocus looks like this:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/5943437/221233684-2292dd9d-a21f-4530-8066-fc21d7b133f0.png">

Then this error occurs:
```
/Users/johnrandall/.rvm/gems/ruby-3.2.1/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: -1728
		MESSAGE: Can't get reference.
		OFFENDING OBJECT: app("/Applications/OmniFocus.app").default_document.flattened_tags["TaskBridge"].tasks["test - sync to GoogleA - has tag"]
		COMMAND: app("/Applications/OmniFocus.app").default_document.flattened_tags["TaskBridge"].tasks["test - sync to GoogleA - has tag"].get()

	from /Users/johnrandall/.rvm/gems/ruby-3.2.1/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:642:in `method_missing'
	from /Users/johnrandall/code/vendor/task_bridge/lib/omnifocus/task.rb:115:in `original_task'
	from /Users/johnrandall/.rvm/gems/ruby-3.2.1/gems/memo_wise-1.7.0/lib/memo_wise.rb:184:in `block in original_task'
	from /Users/johnrandall/.rvm/gems/ruby-3.2.1/gems/memo_wise-1.7.0/lib/memo_wise.rb:183:in `fetch'
	from /Users/johnrandall/.rvm/gems/ruby-3.2.1/gems/memo_wise-1.7.0/lib/memo_wise.rb:183:in `original_task'
	from /Users/johnrandall/code/vendor/task_bridge/lib/omnifocus/task.rb:99:in `flag!'
	from /Users/johnrandall/code/vendor/task_bridge/lib/google_tasks/service.rb:67:in `add_task'
	from /Users/johnrandall/code/vendor/task_bridge/lib/google_tasks/service.rb:50:in `block in sync_from_primary'
	from /Users/johnrandall/code/vendor/task_bridge/lib/google_tasks/service.rb:44:in `each'
	from /Users/johnrandall/code/vendor/task_bridge/lib/google_tasks/service.rb:44:in `sync_from_primary'
	from /Users/johnrandall/code/vendor/task_bridge/lib/task_bridge.rb:89:in `block in call'
	from /Users/johnrandall/code/vendor/task_bridge/lib/task_bridge.rb:73:in `each'
	from /Users/johnrandall/code/vendor/task_bridge/lib/task_bridge.rb:73:in `call'
	from bin/task_bridge:6:in `<main>'
```

Adding the missing "TaskBridge" tag to "sync test 2  - has tag" in OmniFocus seems to fix the problem.

**Comment by viamin** [comment]
I think this was fixed by https://github.com/viamin/task_bridge/pull/110. We now search for a task by ID. In this case, the task won't be found, because the Omnifocus task doesn't have the TaskBridge tag, but it should no longer crash.
